<a href="https://colab.research.google.com/github/AayushMishragit/AayushMishragit/blob/main/customer_behaviour%5BEDA%5D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [11]:
# sample dataset
data = {
    "customer_id": [
        "CUST_1000", "CUST_1001", "CUST_1002", "CUST_1003", "CUST_1004",
        "CUST_1005", "CUST_1006", "CUST_1007", "CUST_1008", "CUST_1009",
        "CUST_1010", "CUST_1011", "CUST_1012", "CUST_1013", "CUST_1014"
    ],
    "age": [38, 20, 40, 49, 31, 24, 33, 42, 27, 55, 36, 29, 45, 22, 39],
    "gender": [
        "Male", "Female", "Female", "Male", "Female",
        "Non-Binary", "Male", "Female", "Male", "Female",
        "Male", "Female", "Male", "Female", "Male"
    ],
    "membership_tier": [
        "Bronze", "Silver", "Bronze", "Gold", "Platinum",
        "Bronze", "Silver", "Gold", "Bronze", "Silver",
        "Platinum", "Bronze", "Gold", "Silver", "Bronze"
    ],
    "device_type": [
        "Desktop", "Mobile", "Mobile", "Desktop", "Mobile",
        "Tablet", "Mobile", "Desktop", "Mobile", "Desktop",
        "Mobile", "Mobile", "Desktop", "Mobile", "Tablet"
    ],
    "payment_method": [
        "Credit Card", "UPI", "Debit Card", "Credit Card", "UPI",
        "Net Banking", "Credit Card", "UPI", "Debit Card", "Credit Card",
        "UPI", "UPI", "Net Banking", "Debit Card", "Credit Card"
    ],
    "annual_income_k": [41.9, 28.4, 35.1, 62.8, 78.2, 22.5, 48.0, 55.4, 31.0, 50.2, 89.5, 27.8, 68.1, 33.4, 39.6],
    "app_sessions_per_month": [13, 18, 14, 11, 22, 9, 17, 12, 15, 10, 25, 12, 13, 19, 8],
    "avg_session_duration_min": [20.2, 11.5, 9.8, 24.1, 14.3, 13.1, 10.6, 28.5, 8.9, 22.0, 16.2, 9.1, 26.4, 12.0, 15.8],
    "total_purchases": [4, 5, 3, 4, 7, 2, 4, 5, 3, 3, 8, 2, 5, 6, 2],
    "total_spent": [312.45, 420.80, 185.20, 890.50, 2150.10, 95.60, 510.30, 1120.75, 210.00, 480.90, 2890.40, 140.25, 1350.00, 580.60, 130.80],
    "avg_rating_given": [4.2, 4.8, 3.6, 4.5, 4.9, 2.8, 4.1, 4.6, 3.9, 4.0, 5.0, 3.2, 4.4, 4.3, 3.1],
    "churned": [0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1]
}

df = pd.DataFrame(data)

print(df.to_string(index=False))

customer_id  age     gender membership_tier device_type payment_method  annual_income_k  app_sessions_per_month  avg_session_duration_min  total_purchases  total_spent  avg_rating_given  churned
  CUST_1000   38       Male          Bronze     Desktop    Credit Card             41.9                      13                      20.2                4       312.45               4.2        0
  CUST_1001   20     Female          Silver      Mobile            UPI             28.4                      18                      11.5                5       420.80               4.8        0
  CUST_1002   40     Female          Bronze      Mobile     Debit Card             35.1                      14                       9.8                3       185.20               3.6        1
  CUST_1003   49       Male            Gold     Desktop    Credit Card             62.8                      11                      24.1                4       890.50               4.5        0
  CUST_1004   31     Female        Platinum      Mobile            UPI             78.2                      22                      14.3                7      2150.10               4.9        0
  CUST_1005   24 Non-Binary          Bronze      Tablet    Net Banking             22.5                       9                      13.1                2        95.60               2.8        1
  CUST_1006   33       Male          Silver      Mobile    Credit Card             48.0                      17                      10.6                4       510.30               4.1        0
  CUST_1007   42     Female            Gold     Desktop            UPI             55.4                      12                      28.5                5      1120.75               4.6        0
  CUST_1008   27       Male          Bronze      Mobile     Debit Card             31.0                      15                       8.9                3       210.00               3.9        0
  CUST_1009   55     Female          Silver     Desktop    Credit Card             50.2                      10                      22.0                3       480.90               4.0        0
  CUST_1010   36       Male        Platinum      Mobile            UPI             89.5                      25                      16.2                8      2890.40               5.0        0
  CUST_1011   29     Female          Bronze      Mobile            UPI             27.8                      12                       9.1                2       140.25               3.2        1
  CUST_1012   45       Male            Gold     Desktop    Net Banking             68.1                      13                      26.4                5      1350.00               4.4        0
  CUST_1013   22     Female          Silver      Mobile     Debit Card             33.4                      19                      12.0                6       580.60               4.3        0
  CUST_1014   39       Male          Bronze      Tablet    Credit Card             39.6                       8                      15.8                2       130.80               3.1        1

In [12]:
#select the particular data section
df['age']
#distribution into segments = binning
age_bins = [18, 25, 35, 45, 55]
age_labels = ["18–25", "26–35", "36–45", "46–55"]
df["age_group"] = pd.cut(
    df["age"],
    bins=age_bins,
    labels=age_labels,
    include_lowest=True
)

age_analysis = df["age_group"].value_counts().sort_index()

0     38
1     20
2     40
3     49
4     31
5     24
6     33
7     42
8     27
9     55
10    36
11    29
12    45
13    22
14    39
Name: age, dtype: int64

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               15 non-null     object
 1   age                       15 non-null     int64
 2   gender                    15 non-null     object
 3   membership_tier           15 non-null     object
 4   device_type               15 non-null     object
 5   payment_method            15 non-null     object
 6   annual_income_k           15 non-null     float64
 7   app_sessions_per_month    15 non-null     int64
 8   avg_session_duration_min  15 non-null     float64
 9   total_purchases           15 non-null     int64
 10  total_spent               15 non-null     float64
 11  avg_rating_given          15 non-null     float64
 12  churned                   15 non-null     int64
dtypes: float64(4), int64(4), object(5)
memory usage: 1.7+ KB

,age,annual_income_k,app_sessions_per_month,avg_session_duration_min,total_purchases,total_spent,avg_rating_given,churned
count,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000
mean,35.333333,47.460000,14.533333,16.166667,4.200000,764.576667,4.093333,0.266667
std,10.104219,19.877043,4.838339,6.527378,1.820518,815.389162,0.670252,0.457738
min,20.000000,22.500000,8.000000,8.900000,2.000000,95.600000,2.800000,0.000000
25%,28.000000,32.200000,11.500000,11.050000,3.000000,197.600000,3.750000,0.000000
50%,36.000000,41.900000,13.000000,14.300000,4.000000,480.900000,4.200000,0.000000
75%,41.000000,59.100000,17.500000,21.100000,5.000000,1005.625000,4.550000,0.500000
max,55.000000,89.500000,25.000000,28.500000,8.000000,2890.400000,5.000000,1.000000